### ISSUE TITLE
Make cleaning optional

### ISSUE THREAD

**Issue by fdiblen** [tortellini-tools/action#120]
Removing `in/` folder and intermediate files in `out/` folder should be controlled by an input to the action.

Example:
```yaml
    - uses: tortellini-tools/action@main
      with:
        keep_intermediate: true
```

**Comment by jspaaks** [comment]
Maybe instead of boolean flags we could have an array with strings from an enum, like

```yaml
    - uses: tortellini-tools/action@main
      with:
        keep:
          - clone
          - analyze
          - gitlab
```
anbd then somewhere in the code
```typescript
if ('clone' in keep) {
    // keep clone results
} else {
    // throw away clone results
}


if ('gitlab' in keep) {
    // keep gitlab results
} else {
    // throw away gitlab results
}

// etc
```
