### ISSUE TITLE
make docker image an argument?

### ISSUE THREAD

**Issue by jspaaks** [tortellini-tools/action#154]
https://github.com/tortellini-tools/action/blob/cffde325acfe877b62c902002c071db9e464c470/src/docker.ts#L13

soimething like

```yaml
- uses: tortellini-tools/action@v3
  with:
    repositories: urls.txt
    image: philipssoftware/ort:2021-05-23
```
