### ISSUE TITLE
Add list of representative repos, with expected result

### ISSUE THREAD

**Issue by jspaaks** [tortellini-tools/action#17]
Should we add a list of repositories with expected result so we can better compare the various license clash tools we find? Something like:

```yaml
fair-software/howfairis: 
  - backoff
  - beautifulsoup4
  - click
  - colorama
  - docutils
  - pygments
  - ratelimit
  - requests
  - ruamel.yaml
  - voluptuous
  - bumpversion
  - prospector[with_pyroma]
  - pycodestyle
  - pytest-cov
  - pytest-runner
  - pytest
  - recommonmark
  - requests_mock
  - sphinx_rtd_theme
  - sphinx-click
  - sphinx
  - yapf
  - twine
  - wheel
fair-software/matchms:
  - etc
```
