### ISSUE TITLE
Instructions how to schedule your repositories for checking

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#39]
As a program manager I would like to know how get my projects repositories to be checked for license problems and see the results some where. Can this be documented.

**Comment by sverhoeven** [comment]
These should be instruction that you should add software to https://www.research-software.nl/ and wait a week.

**Comment by jspaaks** [comment]
Wouldn't this already be solved by offering engineers the exact same tool that programme managers depend on: only difference is that engineers enable it on one of their repositories using a GitHub Action, whereas programme managers depend on the results of a weekly run done on all repositories?

**Comment by sverhoeven** [comment]
The action we are making now is for a set of repositories.We could add an example workflow to the README describing how to use the action in their own repo. Something like
```
steps:
 - name: Prep repo list with self
   run: echo "https://github.com/${{ github.repository_owner }}" > myrepo.txt
 - name: Run ort
   uses: tortellini-tools/action@main
        with:
           repositories: myrepo.txt
           outputdir: results
 - name: Upload ort results of my repo
   uses: actions/upload-artifact@v2
      with:
        name: batchort-results
        path: results/${{ github.repository_owner }}/*
```
We can ignore the index.html page and directly view `scan-report-web-app.html` as its only a single repo.
