### ISSUE TITLE
Reduce number of license issue by improving config files

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#46]
Running ort on RSD software items raised a bunch of UNHANDLED_LICENSE issues.

For example in `iomega/paired-data-form/evaluation-result.yml` I got a lot of:
```yaml
  - rule: "UNHANDLED_LICENSE"
    pkg: "NPM::yargs-parser:20.2.4"
    license: "ISC"
    license_source: "DECLARED"
    severity: "ERROR"
    message: "The license ISC is currently not covered by policy rules. The license\
      \ was declared in package NPM::yargs-parser:20.2.4"
    how_to_fix: "A text written in MarkDown to help users resolve policy violations\n\
      which may link to additional resources."
```

All unhandled licences are:
```
grep -hA 2 UNHANDLED_LICENSE */*/evaluation-result.yml |grep  'license:'| sort |uniq -c |sort -nr
   1306     license: "ISC"
     79     license: "PSF-2.0"
     44     license: "LicenseRef-scancode-public-domain-disclaimer"
     16     license: "AFL-2.1"
     12     license: "ZPL-2.1"
     10     license: "CPL-1.0"
      8     license: "LicenseRef-scancode-repoze"
      8     license: "HPND"
      8     license: "0BSD"
      4     license: "LicenseRef-scancode-free-unknown"
      2     license: "LicenseRef-ort-unknown-license-reference"
      1     license: "ODC-By-1.0"
      1     license: "LicenseRef-scancode-amazon-sl"
      1     license: "CECILL-2.1"
```

A nice start would be to add licenses that occur a lot (>10 times).

Those license can be handled by ort by adding them to the `license-classifications.yml` config file.
