### ISSUE TITLE
Add input option to run analysis on multiple repository urls

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#75]
Without supplying any input arguments to the action it will run on the currently checkout repo in `.` dir. We would like to able to run the ort analysis on more than one repository. 

For this we want to call the action like this:

Prep repos text file
```
echo 'https://github.com/tortellini-tools/action' > urls.txt
echo 'https://github.com/fair-software/howfairis' >> urls.txt
```

Inside a GH workflow run action like
```
- name: Run ort on urls
  uses: tortellini-tools/action@main
  with:
    repositories: urls.txt
```

This should produce the following files
```
out/ortellini-tools/action/analyzer-result.yml
out/fair-software/howfairis/analyzer-result.yml
```
