### ISSUE TITLE
Configurable output directory

### ISSUE THREAD

**Issue by sverhoeven** [tortellini-tools/action#85]
The action currently creates its output files in the `out` directory. The output directory is currently hard-coded. When a repo already has a `out` dir then this will cause a confusing overlap. It would be nice if the output directory could be altered. 

For example with

```
- name: Run ort on urls
  uses: tortellini-tools/action@main
  with:
    output-dir: output
```

Which when action has completed should have written `output/analyzer-result.yml`.
